---
sudo: required

addons:
  apt:
    packages:
      - docker-ce

services:
  - docker

env:
  - DISTRO=jessie
  - DISTRO=stretch
  - DISTRO=buster
  - DISTRO=trusty
  - DISTRO=xenial
  - DISTRO=bionic

script:
  - make build-$DISTRO
  - make test-$DISTRO


